language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=1.11.2

# addons:
#  apt_packages:
#     - libssl-dev
#     - libcups2-dev

services:
  - mysql

install:
  - pip install --upgrade pip
  - pip install -q Django==$DJANGO_VERSION
  - pip install flake8
  - pip install coveralls
#  - pip install pycups
  - pip install mysql-python
  - pip install -q -r requirements.txt

before_script:
  - flake8 edc_lab
  - mysql -e 'create database edc character set utf8;'

script: 
  - coverage run --source=edc_lab manage.py test

after_success:
  - coveralls
